/// Flutter icons FlinnitIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlinnitIcon
///      fonts:
///       - asset: fonts/FlinnitIcon.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class FlinnitIcon {
  FlinnitIcon._();

  static const _kFontFam = 'FlinnitIcon';
  static const String? _kFontPkg = null;

  static const IconData comment = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__1_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teenyicons_chat_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
